services:
    api:
        build:
            context: ./docker/api
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./api:/app
        working_dir: /app
